### ISSUE TITLE
A Parser-blocking, cross-origin script is invoked via document.write....

### ISSUE THREAD

**Issue by CKDProductions** [olegkoval/magento-product_review_captcha#10]
I'm seeing this alert in my console while using the review captcha (version 1.2.1)

A Parser-blocking, cross-origin script, https://www.google.com/recaptcha/api/js/recaptcha.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity. See https://www.chromestatus.com/feature/5718547946799104 for more details.

Thoughts? Thank you.

**Comment by olegkoval** [comment]
Hello Kevin.

Thank you for email.

Please update extension to version 1.3.0 (
https://github.com/olegkoval/magento-product_review_captcha/releases or
through Magento Connect) - this will fix http/https CORS issue.

Best regards,
Oleg Koval

**Comment by CKDProductions** [comment]
Worked great. Thanks!
