### ISSUE TITLE
ReCaptcha Non-obligatory

### ISSUE THREAD

**Issue by listedegarde** [olegkoval/magento-product_review_captcha#6]
I have installed the plugin, and almost everything works perfectly.  The only problem is that I can still submit product reviews without filling in the captcha.  I'm using Magento 1.8.1, and added the following line into app/design/frontend/base/default/template/productreviewcaptcha/form.phtml inside of the <form> tag:

<?php echo $this->getBlockHtml('formkey'); ?>

Any suggestions?

**Comment by olegkoval** [comment]
Hi.

Looks like you have other custom extension which also extend Product Review
Controller and load before mine extension. That is why you can submit form
without captcha field.

Please check code of your Magento instance and try to find this line of
code (use global search in all files from app/code/ folder):
 extends Mage_Review_ProductController

Then, please, post here results.

Thank you.

Best regards,
Oleg Koval

**Comment by listedegarde** [comment]
Thanks for the reply!  That was it.  I thought I had disabled the other modules I tried, but I missed one.  Thank you for your help.
