### ISSUE TITLE
MagentoCommerce Issue

### ISSUE THREAD

**Issue by vfdev** [olegkoval/magento-product_review_captcha#9]
I was going to open a new PR for some modifications for the newer versions of Magento but I noticed that the repository already has them. However, the MagentoCommerce install does not and I was not sure if you were aware that the connect manager needed to be updated.

Thanks for the extension!

**Comment by olegkoval** [comment]
Hello.
Thank You for comment.
Extension was updated here and on MagentoConnect (https://www.magentocommerce.com/magento-connect/product-review-captcha-1.html). If you need extension for Magento2 then need to create it from scratch.
